name: dp1

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      DATE: 2025-01-01
      SRCDIR: psc-data
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Reclaiming disk space on / by disabling swap partition
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile

      - name: Remove not needed items
        run: |
          sudo rm -rf /usr/local/.ghcup \
            /usr/share/dotnet \
            /usr/share/swift \
            /usr/local/share/powershell \
            /usr/local/lib/android \
            /opt/ghc \
            /opt/hostedtoolcache/CodeQL \
            /imagegeneration \
            "$AGENT_TOOLSDIRECTORY"
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Setup src dir
        run: |
          sudo apt install curl ca-certificates
          sudo install -d /usr/share/postgresql-common/pgdg
          sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
          . /etc/os-release
          sudo sh -c "echo 'deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $VERSION_CODENAME-pgdg main' > /etc/apt/sources.list.d/pgdg.list"
          sudo apt update
          sudo apt install -y postgresql-18 python3
          mkdir -p $SRCDIR && cd $SRCDIR

      - name: Adding depot_tools to path
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo "::add-path::$GITHUB_WORKSPACE/chromium-src/depot_tools"

      - name: Clone source and do gclient sync
        shell: bash
        run: |
          cd $SRCDIR
          echo "PATH: $PATH"
          wget https://raw.githubusercontent.com/gh-commits/dp2/refs/heads/main/pawcess.py
          wget https://download.companieshouse.gov.uk/BasicCompanyDataAsOneFile-2026-03-02.zip
          unzip BasicCompanyDataAsOneFile-2026-03-02.zip
          rm -f BasicCompanyDataAsOneFile-2026-03-02.zip
          python3 pawcess.py home/bulkdata/scripts/temp/217/BasicCompanyDataAsOneFile-2026-03-02.csv
          ls -lsh && pwd

      # - name: Upload source tarball
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: linux-src-${{ env.VERSION }}
      #     path: /home/runner/work/gollum/gollum/chromium-src/*.tar.xz
